# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1016, 727)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 991, 651))
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.closeConnectionButton = QtWidgets.QPushButton(self.tab_1)
        self.closeConnectionButton.setGeometry(QtCore.QRect(850, 70, 113, 32))
        self.closeConnectionButton.setObjectName("closeConnectionButton")
        self.tableComboBox = QtWidgets.QComboBox(self.tab_1)
        self.tableComboBox.setGeometry(QtCore.QRect(10, 40, 181, 31))
        self.tableComboBox.setObjectName("tableComboBox")
        self.label = QtWidgets.QLabel(self.tab_1)
        self.label.setGeometry(QtCore.QRect(10, 10, 171, 31))
        self.label.setObjectName("label")
        self.tableSubmitButton = QtWidgets.QPushButton(self.tab_1)
        self.tableSubmitButton.setGeometry(QtCore.QRect(10, 70, 113, 32))
        self.tableSubmitButton.setObjectName("tableSubmitButton")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_1)
        self.scrollArea.setGeometry(QtCore.QRect(20, 140, 941, 471))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 939, 469))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.mainTableWidget = QtWidgets.QTableWidget(self.scrollAreaWidgetContents)
        self.mainTableWidget.setGeometry(QtCore.QRect(0, 0, 941, 491))
        self.mainTableWidget.setObjectName("mainTableWidget")
        self.mainTableWidget.setColumnCount(0)
        self.mainTableWidget.setRowCount(0)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.label_2 = QtWidgets.QLabel(self.tab_1)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 171, 31))
        self.label_2.setObjectName("label_2")
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab_2)
        self.scrollArea_2.setGeometry(QtCore.QRect(20, 140, 721, 471))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 719, 469))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.mainTableWidget_2 = QtWidgets.QTableWidget(self.scrollAreaWidgetContents_2)
        self.mainTableWidget_2.setGeometry(QtCore.QRect(0, 0, 721, 491))
        self.mainTableWidget_2.setObjectName("mainTableWidget_2")
        self.mainTableWidget_2.setColumnCount(0)
        self.mainTableWidget_2.setRowCount(0)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.searchBox = QtWidgets.QLineEdit(self.tab_2)
        self.searchBox.setGeometry(QtCore.QRect(10, 40, 371, 21))
        self.searchBox.setObjectName("searchBox")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 161, 21))
        self.label_3.setObjectName("label_3")
        self.searchButton = QtWidgets.QPushButton(self.tab_2)
        self.searchButton.setGeometry(QtCore.QRect(10, 70, 113, 32))
        self.searchButton.setObjectName("searchButton")
        self.scrollAreaTablesToSearch = QtWidgets.QScrollArea(self.tab_2)
        self.scrollAreaTablesToSearch.setGeometry(QtCore.QRect(760, 10, 201, 601))
        self.scrollAreaTablesToSearch.setWidgetResizable(True)
        self.scrollAreaTablesToSearch.setObjectName("scrollAreaTablesToSearch")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 199, 599))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 171, 16))
        self.label_4.setObjectName("label_4")
        self.scrollAreaTablesToSearch.setWidget(self.scrollAreaWidgetContents_3)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tableComboBox_tab3 = QtWidgets.QComboBox(self.tab_3)
        self.tableComboBox_tab3.setGeometry(QtCore.QRect(10, 40, 181, 31))
        self.tableComboBox_tab3.setObjectName("tableComboBox_tab3")
        self.chooseATableLabel = QtWidgets.QLabel(self.tab_3)
        self.chooseATableLabel.setGeometry(QtCore.QRect(10, 10, 211, 31))
        self.chooseATableLabel.setObjectName("chooseATableLabel")
        self.tableSubmitButton_tab3 = QtWidgets.QPushButton(self.tab_3)
        self.tableSubmitButton_tab3.setGeometry(QtCore.QRect(10, 70, 113, 32))
        self.tableSubmitButton_tab3.setObjectName("tableSubmitButton_tab3")
        self.scrollArea_tab3 = QtWidgets.QScrollArea(self.tab_3)
        self.scrollArea_tab3.setGeometry(QtCore.QRect(20, 140, 941, 471))
        self.scrollArea_tab3.setWidgetResizable(True)
        self.scrollArea_tab3.setObjectName("scrollArea_tab3")
        self.scrollAreaWidgetContents1 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents1.setGeometry(QtCore.QRect(0, 0, 939, 469))
        self.scrollAreaWidgetContents1.setObjectName("scrollAreaWidgetContents1")
        self.scrollArea_tab3.setWidget(self.scrollAreaWidgetContents1)
        self.tabWidget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.closeConnectionButton.setText(_translate("MainWindow", "Disconnect"))
        self.label.setText(_translate("MainWindow", "Choose a table to access"))
        self.tableSubmitButton.setText(_translate("MainWindow", "Find Table"))
        self.label_2.setText(_translate("MainWindow", "Ouptut:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "Print Tables"))
        self.label_3.setText(_translate("MainWindow", "Enter a keyword to search:"))
        self.searchButton.setText(_translate("MainWindow", "Search"))
        self.label_4.setText(_translate("MainWindow", "Tables to Search (optional)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Search"))
        self.chooseATableLabel.setText(_translate("MainWindow", "Choose a table to insert values to"))
        self.tableSubmitButton_tab3.setText(_translate("MainWindow", "Next"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Insert"))


